### ISSUE TITLE
Duplicate model and 2 face_restore directories

### ISSUE THREAD

**Issue by coreyryanhanson** [Comfy-Org/ComfyUI-Manager#105]
I noticed in the model list there is one section for face_restore that defaults to a face_restore directory:
https://github.com/ltdrdata/ComfyUI-Manager/blob/0d50544287da108dc7992a04925ee97df319f087/model-list.json#L93C1-L122C7

But also at the same time there appears to be a newer addition where models are saved to the face_restore_models directory:
https://github.com/ltdrdata/ComfyUI-Manager/blob/0d50544287da108dc7992a04925ee97df319f087/model-list.json#L1137C5-L1176C7

Existing in both is GFPGANv1.4 (but implying a later release in the hyperlink on the second one)

Is there a reason to keep both sections unconsolidated or is the first face_restore output path planned to be deprecated?

**Comment by ltdrdata** [comment]
Unfortunately, the problem lies in the fact that custom nodes require different paths.
`face_restore` is the path used in the `MTB` node, while `facerestore_models` is the path used in the later added `Facerestore CF (Code Former)` node.

Due to this reason, there are several duplicate items available for download for each path.

**Comment by coreyryanhanson** [comment]
Makes sense. Hopefully in the future one of the paths will win out
