### ISSUE TITLE
#306 ComfyUI Layer Style - Version downgrade

### ISSUE THREAD

**Issue by DeepSeaCatz** [Comfy-Org/ComfyUI-Manager#1119]
I was trying a workflow that required this Custom Node. When installing, it downgraded many package version and it took me 2hours of tinkering to get my Comfy running again.

Should these Custom Nodes that automatically downgrade your versions be allowed on the Manager? Should there be a warning to advise people that this might mess up your Comfy?

These were the 2 custom nodes.
[https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes](https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes)
[https://github.com/chflame163/ComfyUI_LayerStyle](https://github.com/chflame163/ComfyUI_LayerStyle)

I guess we learn every day

**Comment by ltdrdata** [comment]
Based on the requirements.txt, there doesn't seem to be any significant issue.
(numpy is intentionally set to use a lower version because versions 2.0 and above cause many problems.)
Which packages were downgraded due to the installation of these custom nodes?

**Comment by DeepSeaCatz** [comment]
I'm not 100% certain, but I had to reinstall torch, torchvision and torchaudio. I kept getting suggestions to simply install them, but it wouldn't work.
This command helped a lot to re-initiate torch to the right version.
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

fairscale was also downgraded to 0.4.0, to be compatible with torchscale 0.3.0, but I needed fairscale 0.4.13 for comfy to run.
Had to remove many new folders in the `\python_embeded\Lib\site-packages` that had `~` as prefix
I think there was also a package called CV or OpenCV that I had issue with the compatible versions

Trying new custom nodes is like a Lottery. You might win or go in debt and work your way back up.

**Comment by DeepSeaCatz** [comment]
Basically my afternoon last night:
[https://civitai.com/images/33318142](https://civitai.com/images/33318142)

I'll have to be more careful when trying new custom nodes

**Comment by ltdrdata** [comment]
In fact, from the Node developer's perspective, they did their best since they didn't do any special version pinning in `requirements.txt`.
It seems I need to consider how to handle the issue of certain dependencies downgrading other dependencies.

There are a few approaches that come to mind, but each approach brings its own set of problems, making none of them entirely clean or straightforward. I should try to find the method that causes the least problems from the perspective of the average user.

**Comment by PrometheusDante** [comment]
I am having the same issue of getting my torch downgraded to 2.3.1 everytime I use the "Update All" function, so I need to manually pip install it up to 2.5.1 again everytime, as Comfy would not even startup otherwise.
After checking the entire custom_nodes folder for all requirements.txt files containing "torch" and looking specifically for ones specifying exact version dependencies I found:

**• ComfyUI_LayerStyle**
`ComfyUI\custom_nodes\ComfyUI_LayerStyle\py\evf_sam\model\unilm\beit3\requirements.txt`

> --extra-index-url https://download.pytorch.org/whl/cu118
> torch==2.0.1
> --extra-index-url https://download.pytorch.org/whl/cu118
> torchvision==0.15.2
> numpy<2
> opencv-python
> timm
> scipy
> scikit-image
> kornia
> 
> tqdm
> prettytable
> 
> huggingface_hub


**• comfyui_controlnet_aux**
`custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\depth_anything\torchhub\facebookresearch_dinov2_main\requirements.txt`

> --extra-index-url https://download.pytorch.org/whl/cu117
> torch==2.0.0
> torchvision==0.15.0
> omegaconf
> torchmetrics==0.10.3
> fvcore
> iopath
> xformers==0.0.18
> submitit
> --extra-index-url https://pypi.nvidia.com
> cuml-cu11

**Comment by ltdrdata** [comment]
After `manager-core` migration is completed, measures will be in place to recover if PyTorch breaks down, so this issue will be completely resolved.
