### ISSUE TITLE
Custom nodes that are not appearing in the manager: 1) can we trust them? 2) why are they not in the manager?

### ISSUE THREAD

**Issue by moreAImore** [Comfy-Org/ComfyUI-Manager#1212]
For example: https://github.com/neuratech-ai/ComfyUI-MultiGPU
I loaded a workflow that uses nodes from this page.
I installed missing custom nodes, until I had only these, but the manager would not find this custom node!

I have to install it manually
But it seems suspicious, especially since it affects GPU and all that stuff.
![image](https://github.com/user-attachments/assets/bae4ce4c-c250-45b2-8fc7-caf73984fc63)

- Why is it not in the manager?
- Can it be trusted and if it's no in the manager, is it a sign that someone has to be extra careful?

**Comment by ltdrdata** [comment]
It is simply an experimental node provided for multi-gpu environments.

Since it's not a stable node, it has been registered in the dev channel of ComfyUI-Manager.
Code review shows that it's not a dangerous node. However, if you don't have a multi-gpu environment, there's no need to use it.

You can just use the corresponding regular nodes instead.

**Comment by moreAImore** [comment]
Thank you!
