### ISSUE TITLE
Default Cache Updated in ComfyUI manager is causing the GUI not to be shown 

### ISSUE THREAD

**Issue by Bahri-19** [Comfy-Org/ComfyUI-Manager#1320]
Server is starting correctly but not opening the GUI

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

**Comment by ltdrdata** [comment]
The default cache update is performed asynchronously in the background by **ComfyUI-Manager** and is unrelated to whether **ComfyUI** launches or not.

If you are referring to the browser not opening automatically, that only happens when running with `--windows-standalone-build` on Windows.

If no screen appears when accessing **http://127.0.0.1:8188/**, you should test it after disabling all custom nodes.
