### ISSUE TITLE
[Bug]: Skip update check and DB settings are not saved

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI-Manager#1322]
I just discovered by accident that `Skip update check` and `DB` are not saved in settings.

In the video, I also changed `Channel` setting just to compare that all the others are saved correctly.

https://github.com/user-attachments/assets/2b228988-6a6a-4e38-afc7-43731a22a84f

**Comment by ltdrdata** [comment]
Ah, I had forgotten about this.  

That part was actually intentional.  

In environments like Colab + GDrive, visiting every custom node directory to perform a `git fetch` incurs a significant cost. The same applies depending on the network conditions.  

Therefore, by default, the update check is skipped. However, if the user explicitly performs an update and the update is detected, the skip update check is deactivated.
