### ISSUE TITLE
Sorting and Last update

### ISSUE THREAD

**Issue by cchance27** [Comfy-Org/ComfyUI-Manager#187]
Any chance the comfy manager could be sortable by the last update time of the plugins, as it would be interesting to be able to at a glance see what new release have happened since the last update

**Comment by ltdrdata** [comment]
I do plan to implement it later.

**Comment by BuildBackBuehler** [comment]
Great idea for sure. 

I'd also like to re-propose some sort of Git Wiki or something of that nature to enable users to do the legwork with improving descriptions for nodes. 

I'd spent the past 2 days fiddling with the unfinished/abandoned asymmetrical tiling node, hoping to get it to work. Now I just stumbled upon Jags' Vector Magic Node which has a working implementation (though I'm just stoked to have a solution, no fiddle needed!). I also somehow missed Dave's Custom Node (well, the vanilla, indescript title doesn't help 😂) which puts me 1000% over the hump with meeting my asym. regional prompting needs. 

So, I know you wanted to maintain centralization and I do think that's in the community's best interest, so my idea is to basically have the wiki work like a pseudo pull request. Someone has the motive or writing abilities to best describe a CN to its fullest, while another member tags core functionalities (for the overlap warnings). Those updates are reviewed by community members and can be committed just like a pull request hotfix. I figure either a. with the approval of the node's maintainer or b. your approval. 

I think crowdsourcing the knowledge with overlapping functionalities is imperative because I'm sure that the node maintainers with highly niche/complex functionalities are laser-focused on theirs. Doubt they're looking for overlapping nodes. It likely goes without saying that a user may also describe the node in a more colloquial manner which the quickly/easily understood nature to any/all users is preferable. 

Can put this in its own issue of course 😂

**Comment by cchance27** [comment]
I mean realistically you don't need to pull it from wiki, can just use the github repo description used as the description and maybe add a link that pops up the readme.md in a dialog if the person wants to research more from the manager

That way all repo owners need to do is properly maintain their repo name, description and readme which they should be doing and this would give them more reason to do it

Try to keep as much of the items you're using for the manager the default GitHub features and limit the added work maintainers need to do... because most won't do extra to meet comparability beyond the bare minimum

**Comment by gontz** [comment]
First, let me say that the latest update with mentioning of conflicting nodes has made me dance alone in the room. It is super helpful. 
If I may add a little request. can you please link the conflicting nodes? 
As a user I would like to be able to click on the conflicting node and jump to it's position to see if I have installed it and forgot about it.
Thank you

**Comment by BuildBackBuehler** [comment]
> I mean realistically you don't need to pull it from wiki, can just use the github repo description used as the description and maybe add a link that pops up the readme.md in a dialog if the person wants to research more from the manager
> 
> That way all repo owners need to do is properly maintain their repo name, description and readme which they should be doing and this would give them more reason to do it
> 
> Try to keep as much of the items you're using for the manager the default GitHub features and limit the added work maintainers need to do... because most won't do extra to meet comparability beyond the bare minimum

That's the point of my suggestion – it demands less of the node creator to provide detailed descriptions + provide examples, etc. – as providing the node in itself is a great contribution to the community. Makes more sense than forcing/pushing someone who must've had their reasons for not describing the node. They aren't being paid to make 'em, nor to share 'em. 

I think more community involvement would facilitate a lot of improvements. I imagine people who don't have much/any technical prowess would like to give back to the community, and more importantly tbh, Lt. Dr. Data & the node creators. It'd also allow dead nodes – whether it be due to lack of maintenance, deprecation by ComfyUI additions/feature updates or just incomplete ones to be flagged, preferably moved to the bottom of the list (if not removed from the default in-ComfyUI-list/channel entirely). 

Just, of course, for QA/QC, would want moderators aka trusted community members to either be approving these edits or able to override descriptions edits/block errant editors. Unless Lt. Dan wanted that on his/her/their shoulders 🥴

**Comment by ltdrdata** [comment]
This is updated.
https://www.youtube.com/watch?v=syA0Uo6pOKM
