### ISSUE TITLE
Custom custom_nodes directory location not respected from yaml file.

### ISSUE THREAD

**Issue by littleowl** [Comfy-Org/ComfyUI-Manager#212]
The extra_model_paths.yaml custom_nodes: path/custom_nodes is not respected by the manager.
This leads to it being installed in the wrong place, and shows a unusual state rather than it being installed or not.

**Comment by ltdrdata** [comment]
Setting `extra_model_paths.yaml` is only for specifying additional model paths, and it does not replace the existing paths or set paths for custom nodes.

**Comment by ltdrdata** [comment]
I've thought a bit more about the external installation path, and there are nodes that may cause issues if they are not located under ComfyUI/custom_nodes.

In particular, with installations via `install.py`, since it doesn't run within the ComfyUI execution environment, if the location of custom_nodes becomes an arbitrary path, it may misidentify the location of ComfyUI, leading to a chaotic installation state.

Therefore, support for this will not be provided separately.
