### ISSUE TITLE
[Feature Request] Install Models menu - search subdirectories for models that have been relocated.

### ISSUE THREAD

**Issue by ricardofeynman** [Comfy-Org/ComfyUI-Manager#230]
I have a full install of the models available through the Install Models menu list, and use that menu as quick reference daily to keep an eye out for newly supported tools. 

To keep things neat, I like to tidy models into subfolder categories. 

When I do this with any of the models from the Install Models menu, the relocated model shows on the Install Models list as not installed. 

Would it be possible for the manager to check whether the listed models are present in any subdirectories of their expected location?

On a seperate note, the custom node listing 236: "drustan-hawk [primitive-types] (https://github.com/drustan-hawk/primitive-types)" has the same text description as listing 235: "chflame163 [ComfyUI_MSSpeech_TTS] (https://github.com/chflame163/ComfyUI_MSSpeech_TTS)".

Thanks for the manager!

**Comment by ltdrdata** [comment]
Since creators often use default names for models, I identify them with unique names that include the path. The manager takes a conservative view, so if the path changes, it no longer considers it the same model. I don't think it's a significant issue since it's simply an auxiliary feature for downloading models.

**Comment by ricardofeynman** [comment]
Fair. Thanks for the reply.
