### ISSUE TITLE
The ComfyUI-Manager appears to not support custom nodes from extra_model_paths.yaml

### ISSUE THREAD

**Issue by loner233** [Comfy-Org/ComfyUI-Manager#352]
This is a fantastic project that has solved many of my problems. 
I have another question to ask. ComfyUI supports adding additional paths for custom nodes in extra_model_paths.yaml
[extra_model_paths.yaml.example#L42](https://github.com/comfyanonymous/ComfyUI/blob/f2d432f9a754f2bacb85a70f7e2b817e6dba44f8/extra_model_paths.yaml.example#L42). 

I imported a node through this method, and it is functional. (As you can see, the"Comfyui-Manager" and "Comfyui-Impact-Pack" are in `custom_nodes` folder, and the "ComfyUI-VideoHelperSuite" is in `custom_nodes2` folder)
<img width="570" alt="Screenshot 2024-01-22 at 17 56 33" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/16119486/dacd9f01-dafa-4ee2-98d5-264e6e64aa14">
But in the ComfyUI Manager, it is in an uninstalled state.
<img width="1584" alt="image" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/16119486/c7459784-ebb1-46ef-a536-de2d574990a7">

**Comment by ltdrdata** [comment]
Currently, in ComfyUI-Manager, due to various complex situation issues, support for external custom node paths through `extra_model_paths.yaml` is not available.
This calls for some careful consideration and contemplation.

Moreover, even if the Manager supports this approach, scripts like `install.py` that accompany custom nodes operate outside of ComfyUI. As a result, there is a high likelihood of improper identification of the custom_nodes' path, potentially causing some custom nodes to not function properly.

**Comment by loner233** [comment]
Indeed, I did some research on the code related to custom_nodes in both comfyui and comfyui-manager. It is indeed a very complex and extensive task, which may involve many extension developers. 

In some extensions I use, the import statements are like this: import custom_node.xxxx, causing nodes added through extra files to throw exceptions.
