### ISSUE TITLE
## [WARN] ComfyUI-Manager: Your ComfyUI version (1) is too old. - Wrong version detected

### ISSUE THREAD

**Issue by godly** [Comfy-Org/ComfyUI-Manager#363]
To reproduce the issue:
`git clone --depth 1 https://github.com/comfyanonymous/ComfyUI` and then install ComfyUI Manager and start it.

One can easily work around this issue by installing the whole ComgyUI commit history, But as a normal user we likely don't need it, the same should apply to ComfyUi Manager. 

There is also https://github.com/ltdrdata/ComfyUI-Manager/issues/157 . Anyhow I don't have a `ComfyUI/custom_nodes/.ipynb_checkpoint` directory.

The manager will list the ComfyUI version as '1' from 2024-01-xx and claim that it is outdated.
After a `git pull` version will be detected as '2' if there was a new commit.

This seems to be caused by `__init__.py` within `comfy_ui_revision = len(list(repo.iter_commits('HEAD')))` which seems to return 1.
The code `comfy_ui_commit_date = repo.head.commit.committed_datetime.date()` works fine and returns the current date as far as I can tell.

**Comment by ltdrdata** [comment]
Show me the full log.

**Comment by ltdrdata** [comment]
When performing `git clone --depth 1 https://github.com/comfyanonymous/ComfyUI`, the incorrect recognition of the revision occurs due to the absence of past commit history. This is because the version of ComfyUI is determined based on the length of the history in the revision, and in this case, there is no commit history available.

I will consider going by date-based approach.

**Comment by ltdrdata** [comment]
This is fixed.
