### ISSUE TITLE
save as component (group node) will cause all custom information to be lost

### ISSUE THREAD

**Issue by whmc76** [Comfy-Org/ComfyUI-Manager#374]
save as component (group node) will cause all custom information to be lost and will not save all the configuration and data I modified to group node.
I'm not sure if this is the design purpose, but usually we use comfyui to change the configuration data a lot to achieve better functions, such as the delimiter used by split string, or a lot of strings I have written. They are all reset to the node default options or blank string. This makes the group node I saved completely unusable.

**Comment by ltdrdata** [comment]
It's not caused by "save as component." It's a restriction of the group node itself.
When converting to a group node, the settings are preserved for the nodes already present at the moment of conversion, but if you directly add a group node via "add node," you'll notice that it defaults to its default settings.

The improvement regarding this matter should be requested in the ComfyUI repository.

**Comment by akfheaven** [comment]
what I do now is making a workflow storing all custom group nodes and copy from it as a semi-solution.
waiting for a real solution.
