### ISSUE TITLE
Any chance we can add diffusers to the downgrade blacklist?

### ISSUE THREAD

**Issue by clayne** [Comfy-Org/ComfyUI-Manager#515]
There are multiple nodes that try to monkey around with the version installed:
```
clayne@sv590:/f/stablediffusion/ComfyUI/custom_nodes (master=) $ egrep -r '^diffusers[<>~=]' --include=requirements.txt
ComfyUI-3D-Pack.disabled/requirements.txt:diffusers>=0.26.1
comfyui-instantId-faceswap/requirements.txt:diffusers~=0.26.0
ComfyUI-layerdiffuse.disabled/requirements.txt:diffusers>=0.25.0
ComfyUI-Marigold/requirements.txt:diffusers>=0.20.1
```
Now granted, most are not downgrades, but I'm simply proposing to add it to this list:
```
prestartup_script.py:cm_global.pip_downgrade_blacklist = ['torch', 'torchsde', 'torchvision', 'transformers', 'safetensors', 'kornia']
```

**Comment by chalkncheese** [comment]
Have you found a solution to this ? ComfyUI still fails to import "ComfyUI-3d-Pack" and "ComfyUI-ADMotionDirector" complaining about "No module named 'diffusers.models.unets' and ignoring "blacklisted" transformers.

**Comment by ltdrdata** [comment]
I'm somewhat deliberating on this part. Currently, the blacklist consists only of items that are part of the basic requirements of ComfyUI. I'm considering options that allow users to configure through something like a config, because I'm not sure what issues might arise if other packages are included here.

**Comment by ltdrdata** [comment]
This feature is updated.
