### ISSUE TITLE
Derfuu nodes deleted from the db

### ISSUE THREAD

**Issue by piyushK52** [Comfy-Org/ComfyUI-Manager#612]
any reason why derfuu nodes were deleted (commit - ba671ac) ? If it was by mistake then it will be good to have them back as a lot of my workflows are failing

**Comment by ltdrdata** [comment]
> any reason why derfuu nodes were deleted (commit - [ba671ac](https://github.com/ltdrdata/ComfyUI-Manager/commit/ba671ac9de53d413c08f1d3ceae83d2866f4a7a1)) ? If it was by mistake then it will be good to have them back as a lot of my workflows are failing

The mapping file is managed by an automatic script, and the issue arose due to a failure to statically scan when the Derfuu node was updated. There are many inappropriate aspects to automatically collect this updated pattern, so it is currently under consideration.

edit: I've updated it so that nodes starting with `DF_` are recognized as Derfuu nodes. They should now be recognized correctly.
