### ISSUE TITLE
[FEATURE] Allow we to install things manually, while letting me browse the catalogue of options Comfy Has (Alternative to the button "INSTALL")

### ISSUE THREAD

**Issue by StableInfo** [Comfy-Org/ComfyUI-Manager#66]
Hello,
When I click on "Install" button, the download is usualy very slow, I am better doing the git ... url of the extention than waiting for the manager installation, whereas I still find the manager very useful to have a view on everything avalaible.
Is there a way to get the url/link of the git of very extension mentioned directly availble in the list? 

So I can BROWSE using comfy manager, but then I can switch to regular git installation locally if the download speed is too slow with the manager.
Can you implement that? Thanks

**Comment by ltdrdata** [comment]
Clicking on the title usually provides the `git url`. However, the manager goes beyond just performing a `git clone`. It includes the installation of package dependencies in the appropriate Python environment and execution of installation scripts. Due to this, you would need to manually handle these steps.

**Comment by StableInfo** [comment]
Yes, and that kinda raise saferty concerns on my part, especially if the item installed is not verified no?
Clicking title provide the git? okay thanks.
