### ISSUE TITLE
Display exceptions on the front-end

### ISSUE THREAD

**Issue by nono-Sang** [Comfy-Org/ComfyUI-Manager#660]
Hi, I have a need now. My custom node can only support Linux systems. I will make a check in `install.py`. If the user's system is windows, I will throw an `OSError` exception, but I found that it cannot be captured and displayed by the front-end. Is there any way to do it?

**Comment by ltdrdata** [comment]
It is not simple to reflect the execution result of `install.py` to the front-end. Especially in the case of Windows, `install.py` is executed before the server is up and running after restarting.
This requires the introduction of a system that verifies before installation through a separate spec, rather than `install.py`.

**Comment by nono-Sang** [comment]
thanks
