### ISSUE TITLE
Some extensions don't have a node list in `extension-node-map.json`

### ISSUE THREAD

**Issue by liusida** [Comfy-Org/ComfyUI-Manager#745]
I was inspired by https://ltdrdata.github.io/ and have integrated the data from [extension-node-map.json](https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json) to my [top-100-comfyui](https://github.com/liusida/top-100-comfyui/), but I found that it shows that many extensions don't have nodes, for example:

==
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/14249458/395d74b9-51a8-4181-bcc7-d7755f667508)
==
And I looked it up in the original file, it doesn't contain any nodes as well:
```
    "https://github.com/rgthree/rgthree-comfy": [
        [],
        {
            "author": "rgthree",
            "description": "A bunch of nodes I created that I also find useful.",
            "nickname": "rgthree",
            "nodename_pattern": " \\(rgthree\\)$",
            "title": "Comfy Nodes",
            "title_aux": "rgthree's ComfyUI Nodes"
        }
    ],
```

And also https://ltdrdata.github.io/
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/14249458/d1c2da60-26d8-4c33-9e6f-fea164cb0c91)

I think this might be caused by a problem in the information collecting process. Would you like to take a look at it? Thanks!

**Comment by ltdrdata** [comment]
That is a limitation.
https://github.com/ltdrdata/ComfyUI-Manager#custom-node-support-guide

The node names are collected by the `scanner.py` script.
Since it is a script that scans statically, it is not possible to collect node names that are generated dynamically or exist virtually on the JavaScript side.
For those nodes, unless the list is explicitly provided, ComfyUI-Manager cannot provide them either.

Managing those nodes through code review is beyond my capacity.

**Comment by liusida** [comment]
I see. I'll just explain it straight on the page.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/14249458/8bf6950d-36fe-4905-a4b7-d8be984f374c)
